# Example MCDE Configuration (no secrets)

app:
  name: "MCDE"
  version: "1.0.0"
  environment: "production"
  debug: false

api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  timeout: 300
  max_upload_size: "50MB"

document:
  supported_formats: ["pdf", "jpg", "jpeg", "png", "tiff"]
  max_file_size: 52428800
  ocr_confidence_threshold: 0.8
  image_preprocessing:
    resize_width: 1920
    resize_height: 1080
    dpi: 300

ocr:
  engine: "tesseract"
  language: "eng"
  config: "--oem 3 --psm 6"
  timeout: 60

models:
  cost_estimator:
    model_path: "models/cost_model.pkl"
    version: "1.0.0"
    features: ["material_cost", "labor_cost", "overhead_cost", "quantity"]
  validation_model:
    model_path: "models/validation_model.pkl"
    version: "1.0.0"
    confidence_threshold: 0.85

database:
  url: "${MCDE_DATABASE_URL}"
  pool_size: 10
  max_overflow: 20
  echo: false

redis:
  url: "${REDIS_URL}"
  db: 0
  password: null

storage:
  type: "s3"
  bucket: "mcde-documents"
  region: "us-east-1"
  local_path: "data/processed"

refund_engine:
  base_url: "http://refund-engine:8000"
  timeout: 30
  retry_attempts: 3
  api_key: "${REFUND_ENGINE_API_KEY}"

amazon_api:
  base_url: "https://sellingpartnerapi-na.amazon.com"
  region: "us-east-1"
  marketplace_id: "ATVPDKIKX0DER"
  credentials:
    access_key: "${AWS_ACCESS_KEY_ID}"
    secret_key: "${AWS_SECRET_ACCESS_KEY}"
    role_arn: "${AWS_ROLE_ARN}"

compliance:
  amazon_requirements:
    - "document_authenticity"
    - "cost_validation"
    - "manufacturing_verification"
  validation_rules:
    min_cost_threshold: 0.01
    max_cost_threshold: 10000.00
    required_fields: ["invoice_number", "date", "supplier", "total_amount"]

logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file: "logs/mcde.log"
  max_size: "100MB"
  retention: "30 days"

monitoring:
  metrics_port: 9090
  health_check_interval: 30
  performance_thresholds:
    document_processing_time: 60
    ocr_accuracy: 0.85
    cost_prediction_accuracy: 0.90

security:
  encryption_key: "${ENCRYPTION_KEY}"
  jwt_secret: "${JWT_SECRET}"
  cors_origins: "${MCDE_CORS_ORIGINS}"
  rate_limit: 100

feature_store:
  type: "redis"
  prefix: "mcde_features"
  ttl: 86400

audit:
  enabled: true
  log_level: "INFO"
  retention_days: 90
  sensitive_fields: ["credit_card", "ssn", "bank_account"]



