/**
 * Inbound Inspector Adversarial Scenario Library
 * 
 * Version: 1.0 (Flagship 3 Calibration)
 */

import { 
    InboundShipmentItem, 
    InboundReimbursement 
} from '../services/detection/algorithms/inboundAlgorithms';

export interface InboundScenario {
    id: string;
    family: string;
    description: string;
    outcome: 'positive' | 'negative' | 'suppressed';
    
    // Quantitative Ground Truth
    expected_sent_units: number;
    expected_received_units: number;
    expected_reimbursed_units: number; 
    expected_unresolved_units: number;
    expected_claimable_units: number;
    
    physical_truth: string;
    claimable_truth: string;
    expected_value_status: 'none' | 'partial' | 'full';
    rationale: string;
    
    // Inputs (Bundled Events)
    shipment_items: InboundShipmentItem[];
    reimbursements: InboundReimbursement[];
}

const MOCK_SELLER = 'seller-inbound-lab';

const daysAgo = (days: number): string => {
    const d = new Date();
    d.setDate(d.getDate() - days);
    return d.toISOString();
};

export const INBOUND_SCENARIOS: InboundScenario[] = [
    // --- Family 1: Healthy Inbound Flows (5) ---
    { id: 'H1-STANDARD', family: '1: Healthy', description: 'Sent 100, Rec 100, Closed 95d.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 100, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Balanced', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Balanced.', shipment_items: [{ id: 'h1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-H1', sku: 'SKU-H1', quantity_shipped: 100, quantity_received: 100, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'H2-MULTI-SKU', family: '1: Healthy', description: 'Multi-SKU all rec.', outcome: 'negative', expected_sent_units: 200, expected_received_units: 200, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Balanced', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Multi balanced.', shipment_items: [{ id: 'h2-1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-H2', sku: 'SKU-H2A', quantity_shipped: 100, quantity_received: 100, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }, { id: 'h2-2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-H2', sku: 'SKU-H2B', quantity_shipped: 100, quantity_received: 100, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'H3-WORKING', family: '1: Healthy', description: 'WORKING status.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 0, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'In Transit', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Not closed.', shipment_items: [{ id: 'h3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-H3', sku: 'SKU-H3', quantity_shipped: 100, quantity_received: 0, shipment_status: 'WORKING', shipment_created_date: daysAgo(5), created_at: daysAgo(5) }], reimbursements: [] },
    { id: 'H4-OVER-REC', family: '1: Healthy', description: 'Sent 100, Rec 105.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 105, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Over-rec', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Surplus.', shipment_items: [{ id: 'h4', seller_id: MOCK_SELLER, shipment_id: 'SHIP-H4', sku: 'SKU-H4', quantity_shipped: 100, quantity_received: 105, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'H5-RECENT-CLOSED', family: '1: Healthy', description: 'Closed 2d ago (within SLA).', outcome: 'negative', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'In Transit', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Within window.', shipment_items: [{ id: 'h5', seller_id: MOCK_SELLER, shipment_id: 'SHIP-H5', sku: 'SKU-H5', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(10), shipment_closed_date: daysAgo(2), created_at: daysAgo(10) }], reimbursements: [] },

    // --- Family 2: Shipment Shortages (5) ---
    { id: 'S1-SIMPLE', family: '2: Shortages', description: 'Sent 100, Rec 90. 95d ago.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: '10 lost', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Valid shortage.', shipment_items: [{ id: 's1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-S1', sku: 'SKU-S1', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'S2-TOTAL-LOSS', family: '2: Shortages', description: 'Sent 100, Rec 0.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 0, expected_reimbursed_units: 0, expected_unresolved_units: 100, expected_claimable_units: 100, physical_truth: '100 lost', claimable_truth: '100 units', expected_value_status: 'full', rationale: 'Total missing.', shipment_items: [{ id: 's2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-S2', sku: 'SKU-S2', quantity_shipped: 100, quantity_received: 0, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'S3-MULTI-SKU', family: '2: Shortages', description: 'One SKU short.', outcome: 'positive', expected_sent_units: 200, expected_received_units: 190, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: '1 SKU short', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Isolated.', shipment_items: [{ id: 's3-1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-S3', sku: 'SKU-S3A', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }, { id: 's3-2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-S3', sku: 'SKU-S3B', quantity_shipped: 100, quantity_received: 100, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'S4-ADMITTED', family: '2: Shortages', description: 'MISCOUNTED reason.', outcome: 'positive', expected_sent_units: 50, expected_received_units: 45, expected_reimbursed_units: 0, expected_unresolved_units: 5, expected_claimable_units: 5, physical_truth: '5 lost', claimable_truth: '5 units', expected_value_status: 'full', rationale: 'Admitted miscount.', shipment_items: [{ id: 's4', seller_id: MOCK_SELLER, shipment_id: 'SHIP-S4', sku: 'SKU-S4', quantity_shipped: 50, quantity_received: 45, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), discrepancy_reason: 'MISCOUNTED', created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'S5-TINY-SHORTAGE', family: '2: Shortages', description: '1 unit missing.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 99, expected_reimbursed_units: 0, expected_unresolved_units: 1, expected_claimable_units: 1, physical_truth: '1 lost', claimable_truth: '1 unit', expected_value_status: 'full', rationale: 'Precision test.', shipment_items: [{ id: 's5', seller_id: MOCK_SELLER, shipment_id: 'SHIP-S5', sku: 'SKU-S5', quantity_shipped: 100, quantity_received: 99, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },

    // --- Family 3: Partial Reimbursements (5) ---
    { id: 'R1-PARTIAL', family: '3: Partial Reimb', description: '100 sent, 80 rec, 5 paid.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 80, expected_reimbursed_units: 5, expected_unresolved_units: 15, expected_claimable_units: 15, physical_truth: '20 lost, 5 paid', claimable_truth: '15 units', expected_value_status: 'partial', rationale: 'Netting test.', shipment_items: [{ id: 'r1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R1', sku: 'SKU-R1', quantity_shipped: 100, quantity_received: 80, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 're1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R1', sku: 'SKU-R1', reimbursement_amount: 100, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },
    { id: 'R2-LARGE-PARTIAL', family: '3: Partial Reimb', description: '50 lost, 45 paid.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 50, expected_reimbursed_units: 45, expected_unresolved_units: 5, expected_claimable_units: 5, physical_truth: '50 lost, 45 paid', claimable_truth: '5 units', expected_value_status: 'partial', rationale: 'Tight margin.', shipment_items: [{ id: 'r2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R2', sku: 'SKU-R2', quantity_shipped: 100, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 're2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R2', sku: 'SKU-R2', reimbursement_amount: 900, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },
    { id: 'R3-WRONG-SKU-REIMB', family: '3: Partial Reimb', description: 'Shipment has A short, but B reimbursed.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: 'SKU A lost', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Wrong SKU paid.', shipment_items: [{ id: 'r3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R3', sku: 'SKU-R3A', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 're3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R3', sku: 'SKU-R3B', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },
    { id: 'R4-REIMB-NO-SHIP-ID', family: '3: Partial Reimb', description: 'Reimb exists but no ship ID linkage.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 10, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Truly paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Missing ID should not mask truth.', shipment_items: [{ id: 'r4', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R4', sku: 'SKU-R4', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 're4', seller_id: MOCK_SELLER, shipment_id: undefined, sku: 'SKU-R4', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },
    { id: 'R5-MULTIPLE-REIMBS', family: '3: Partial Reimb', description: '2 small reimbursements totaling whole.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 10, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Net paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Aggregation needed.', shipment_items: [{ id: 'r5', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R5', sku: 'SKU-R5', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 're5a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R5', sku: 'SKU-R5', reimbursement_amount: 100, currency: 'USD', reimbursement_date: daysAgo(92), created_at: daysAgo(92) }, { id: 're5b', seller_id: MOCK_SELLER, shipment_id: 'SHIP-R5', sku: 'SKU-R5', reimbursement_amount: 100, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },

    // --- Family 4: Full Reimbursements (3) ---
    { id: 'F1-FULL', family: '4: Full Reimb', description: '10 lost, 10 paid.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 10, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Resolved.', shipment_items: [{ id: 'f1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-F1', sku: 'SKU-F1', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 'ref1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-F1', sku: 'SKU-F1', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },
    { id: 'F2-FULL-MULTI', family: '4: Full Reimb', description: 'Total loss fully paid.', outcome: 'negative', expected_sent_units: 50, expected_received_units: 0, expected_reimbursed_units: 50, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Resolved.', shipment_items: [{ id: 'f2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-F2', sku: 'SKU-F2', quantity_shipped: 50, quantity_received: 0, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 'ref2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-F2', sku: 'SKU-F2', reimbursement_amount: 1000, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },
    { id: 'F3-EXACT-REIMB', family: '4: Full Reimb', description: '5 unit short, 5 unit reimb.', outcome: 'negative', expected_sent_units: 30, expected_received_units: 25, expected_reimbursed_units: 5, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Resolved.', shipment_items: [{ id: 'f3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-F3', sku: 'SKU-F3', quantity_shipped: 30, quantity_received: 25, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 'ref3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-F3', sku: 'SKU-F3', reimbursement_amount: 100, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },

    // --- Family 5: Clawbacks (2) ---
    { id: 'C1-CLAWBACK', family: '5: Clawbacks', description: 'Paid then reversed.', outcome: 'positive', expected_sent_units: 50, expected_received_units: 40, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: '10 lost, net 0 paid', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Net zero reimb.', shipment_items: [{ id: 'c1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-C1', sku: 'SKU-C1', quantity_shipped: 50, quantity_received: 40, shipment_status: 'CLOSED', shipment_created_date: daysAgo(120), shipment_closed_date: daysAgo(115), created_at: daysAgo(120) }], reimbursements: [{ id: 'rec1a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-C1', sku: 'SKU-C1', reimbursement_amount: 180, currency: 'USD', reimbursement_date: daysAgo(100), created_at: daysAgo(100) }, { id: 'rec1b', seller_id: MOCK_SELLER, shipment_id: 'SHIP-C1', sku: 'SKU-C1', reimbursement_amount: -180, currency: 'USD', reimbursement_date: daysAgo(95), created_at: daysAgo(95) }] },
    { id: 'C2-PARTIAL-CLAW', family: '5: Clawbacks', description: 'Paid 10, reversed 5.', outcome: 'positive', expected_sent_units: 50, expected_received_units: 30, expected_reimbursed_units: 5, expected_unresolved_units: 15, expected_claimable_units: 15, physical_truth: '20 lost, 5 paid', claimable_truth: '15 units', expected_value_status: 'partial', rationale: 'Partial reversal.', shipment_items: [{ id: 'c2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-C2', sku: 'SKU-C2', quantity_shipped: 50, quantity_received: 30, shipment_status: 'CLOSED', shipment_created_date: daysAgo(120), shipment_closed_date: daysAgo(115), created_at: daysAgo(120) }], reimbursements: [{ id: 'rec2a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-C2', sku: 'SKU-C2', reimbursement_amount: 180, currency: 'USD', reimbursement_date: daysAgo(100), created_at: daysAgo(100) }, { id: 'rec2b', seller_id: MOCK_SELLER, shipment_id: 'SHIP-C2', sku: 'SKU-C2', reimbursement_amount: -90, currency: 'USD', reimbursement_date: daysAgo(95), created_at: daysAgo(95) }] },

    // --- Family 6: Boundaries (4) ---
    { id: 'B1-89D', family: '6: Boundaries', description: 'Closed 89d.', outcome: 'suppressed', expected_sent_units: 100, expected_received_units: 50, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Within SLA', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Premature.', shipment_items: [{ id: 'b1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-B1', sku: 'SKU-B1', quantity_shipped: 100, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(95), shipment_closed_date: daysAgo(89), created_at: daysAgo(95) }], reimbursements: [] },
    { id: 'B2-91D', family: '6: Boundaries', description: 'Closed 91d.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 50, expected_reimbursed_units: 0, expected_unresolved_units: 50, expected_claimable_units: 50, physical_truth: 'Past SLA', claimable_truth: '50 units', expected_value_status: 'full', rationale: 'Active.', shipment_items: [{ id: 'b2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-B2', sku: 'SKU-B2', quantity_shipped: 100, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(91), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'B3-90D-EXACT', family: '6: Boundaries', description: 'Closed 90.0d.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: 'Edge', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Edge of SLA.', shipment_items: [{ id: 'b3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-B3', sku: 'SKU-B3', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(90), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'B4-SLA-JITTER', family: '6: Boundaries', description: 'Closed 89d, Created 100d.', outcome: 'suppressed', expected_sent_units: 50, expected_received_units: 0, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Within SLA', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Creation date is not trigger.', shipment_items: [{ id: 'b4', seller_id: MOCK_SELLER, shipment_id: 'SHIP-B4', sku: 'SKU-B4', quantity_shipped: 50, quantity_received: 0, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(89), created_at: daysAgo(100) }], reimbursements: [] },

    // --- Family 7: Limbo (3) ---
    { id: 'L1-LIMBO', family: '7: Limbo', description: 'RECEIVING 120d.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 10, expected_reimbursed_units: 0, expected_unresolved_units: 90, expected_claimable_units: 90, physical_truth: 'Stuck', claimable_truth: '90 units', expected_value_status: 'full', rationale: 'Stale status.', shipment_items: [{ id: 'l1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-L1', sku: 'SKU-L1', quantity_shipped: 100, quantity_received: 10, shipment_status: 'RECEIVING', shipment_created_date: daysAgo(120), created_at: daysAgo(120) }], reimbursements: [] },
    { id: 'L2-SHIP-CREATED-LIMBO', family: '7: Limbo', description: 'CREATED 120d.', outcome: 'positive', expected_sent_units: 50, expected_received_units: 0, expected_reimbursed_units: 0, expected_unresolved_units: 50, expected_claimable_units: 50, physical_truth: 'Stuck', claimable_truth: '50 units', expected_value_status: 'full', rationale: 'Never shipped?', shipment_items: [{ id: 'l2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-L2', sku: 'SKU-L2', quantity_shipped: 50, quantity_received: 0, shipment_status: 'CREATED', shipment_created_date: daysAgo(120), created_at: daysAgo(120) }], reimbursements: [] },
    { id: 'L3-IGNORE-RECENT-RECEIVING', family: '7: Limbo', description: 'RECEIVING 5d.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 50, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'In progress', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Fresh activity.', shipment_items: [{ id: 'l3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-L3', sku: 'SKU-L3', quantity_shipped: 100, quantity_received: 50, shipment_status: 'RECEIVING', shipment_created_date: daysAgo(10), created_at: daysAgo(10) }], reimbursements: [] },

    // --- Family 8: Split Receipts (3) ---
    { id: 'SR1-SPLIT', family: '8: Split', description: '50+50 rec.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 100, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Balanced', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Aggregate.', shipment_items: [{ id: 'sr1a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-SR1', sku: 'SKU-SR1', quantity_shipped: 100, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }, { id: 'sr1b', seller_id: MOCK_SELLER, shipment_id: 'SHIP-SR1', sku: 'SKU-SR1', quantity_shipped: 0, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(96) }], reimbursements: [] },
    { id: 'SR2-SPLIT-SHORT', family: '8: Split', description: '50 rec, 20 rec, 30 missing.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 70, expected_reimbursed_units: 0, expected_unresolved_units: 30, expected_claimable_units: 30, physical_truth: '30 lost', claimable_truth: '30 units', expected_value_status: 'full', rationale: 'Aggregate.', shipment_items: [{ id: 'sr2a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-SR2', sku: 'SKU-SR2', quantity_shipped: 100, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }, { id: 'sr2b', seller_id: MOCK_SELLER, shipment_id: 'SHIP-SR2', sku: 'SKU-SR2', quantity_shipped: 0, quantity_received: 20, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(96) }], reimbursements: [] },
    { id: 'SR3-MULTI-ID', family: '8: Split', description: 'Diff item IDs same shipment.', outcome: 'negative', expected_sent_units: 40, expected_received_units: 40, expected_reimbursed_units: 0, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Balanced', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Aggregate.', shipment_items: [{ id: 'sr3a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-SR3', sku: 'SKU-SR3', quantity_shipped: 20, quantity_received: 20, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }, { id: 'sr3b', seller_id: MOCK_SELLER, shipment_id: 'SHIP-SR3', sku: 'SKU-SR3', quantity_shipped: 20, quantity_received: 20, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(99) }], reimbursements: [] },

    // --- Family 9: Linkage (3) ---
    { id: 'LF1-ORPHAN', family: '9: Linkage', description: 'Paid via orphan.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 50, expected_reimbursed_units: 50, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'ID failure.', shipment_items: [{ id: 'lf1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-LF1', sku: 'SKU-LF1', quantity_shipped: 100, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(120), shipment_closed_date: daysAgo(115), created_at: daysAgo(120) }], reimbursements: [{ id: 'relf1', seller_id: MOCK_SELLER, shipment_id: undefined, sku: 'SKU-LF1', reimbursement_amount: 900, currency: 'USD', reimbursement_date: daysAgo(100), created_at: daysAgo(100) }] },
    { id: 'LF2-WRONG-SHIP-ID', family: '9: Linkage', description: 'Reimb with wrong ship ID.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 10, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'ID failure.', shipment_items: [{ id: 'lf2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-LF2-ABC', sku: 'SKU-LF2', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(120), shipment_closed_date: daysAgo(115), created_at: daysAgo(120) }], reimbursements: [{ id: 'relf2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-WRONG-123', sku: 'SKU-LF2', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(100), created_at: daysAgo(100) }] },
    { id: 'LF3-SKU-LINK-FAILURE', family: '9: Linkage', description: 'Reimb with wrong SKU format.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 10, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'SKU mismatch.', shipment_items: [{ id: 'lf3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-LF3', sku: 'SKU-LF3-PRIME', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(120), shipment_closed_date: daysAgo(115), created_at: daysAgo(120) }], reimbursements: [{ id: 'relf3', seller_id: MOCK_SELLER, shipment_id: 'SHIP-LF3', sku: 'SKU-LF3', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(100), created_at: daysAgo(100) }] },

    // --- Family 10: Duplicates (2) ---
    { id: 'D1-DUPE', family: '10: Duplicates', description: 'Dupe item.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: '10 lost', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Dedupe.', shipment_items: [{ id: 'd1a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-D1', sku: 'SKU-D1', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }, { id: 'd1a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-D1', sku: 'SKU-D1', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'D2-REIMB-DUPE', family: '10: Duplicates', description: 'Dupe reimb.', outcome: 'negative', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 10, expected_unresolved_units: 0, expected_claimable_units: 0, physical_truth: 'Paid', claimable_truth: 'None', expected_value_status: 'none', rationale: 'Dedupe.', shipment_items: [{ id: 'd2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-D2', sku: 'SKU-D2', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 'red2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-D2', sku: 'SKU-D2', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }, { id: 'red2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-D2', sku: 'SKU-D2', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },

    // --- Family 11: Cross-Tenant (2) ---
    { id: 'T1-TENANT', family: '11: Tenant', description: 'Seller A vs B.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 50, expected_reimbursed_units: 0, expected_unresolved_units: 50, expected_claimable_units: 50, physical_truth: 'A lost 50', claimable_truth: '50 units', expected_value_status: 'full', rationale: 'Isolation.', shipment_items: [{ id: 't1a', seller_id: MOCK_SELLER, shipment_id: 'SHIP-T1', sku: 'SKU-T1', quantity_shipped: 100, quantity_received: 50, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }, { id: 't1b', seller_id: 'OTHER', shipment_id: 'SHIP-T1', sku: 'SKU-T1', quantity_shipped: 100, quantity_received: 100, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'T2-REIMB-ISOLATION', family: '11: Tenant', description: 'Reimb from other seller.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: '10 lost, other guy paid', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Isolation.', shipment_items: [{ id: 't2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-T2', sku: 'SKU-T2', quantity_shipped: 100, quantity_received: 90, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [{ id: 'ret2', seller_id: 'OTHER', shipment_id: 'SHIP-T2', sku: 'SKU-T2', reimbursement_amount: 200, currency: 'USD', reimbursement_date: daysAgo(90), created_at: daysAgo(90) }] },

    // --- Family 12: Case-Break (2) ---
    { id: 'CB1-MISMATCH', family: '12: Case-break', description: 'One case short.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 90, expected_reimbursed_units: 0, expected_unresolved_units: 10, expected_claimable_units: 10, physical_truth: '1 case lost', claimable_truth: '10 units', expected_value_status: 'full', rationale: 'Case check.', shipment_items: [{ id: 'cb1', seller_id: MOCK_SELLER, shipment_id: 'SHIP-CB1', sku: 'SKU-CB1', quantity_shipped: 100, quantity_received: 90, cases_shipped: 10, quantity_in_case: 10, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] },
    { id: 'CB2-NON-CASE-SHORT', family: '12: Case-break', description: 'Shortage not matching case.', outcome: 'positive', expected_sent_units: 100, expected_received_units: 85, expected_reimbursed_units: 0, expected_unresolved_units: 15, expected_claimable_units: 15, physical_truth: '15 lost', claimable_truth: '15 units', expected_value_status: 'full', rationale: 'Mixed check.', shipment_items: [{ id: 'cb2', seller_id: MOCK_SELLER, shipment_id: 'SHIP-CB2', sku: 'SKU-CB2', quantity_shipped: 100, quantity_received: 85, cases_shipped: 10, quantity_in_case: 10, shipment_status: 'CLOSED', shipment_created_date: daysAgo(100), shipment_closed_date: daysAgo(95), created_at: daysAgo(100) }], reimbursements: [] }
];
